### ISSUE TITLE
Gör frontend design utefter Figma design

### ISSUE THREAD

**Issue by saraSilvade** [axxcident/gomoku-gurus#10]
skapa front-end design baserad på figma design

**Comment by axxcident** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gör frontend design utefter Figma design](https://trello.com/c/Nzhb74LD/19-g%C3%B6r-frontend-design-utefter-figma-design)

**Comment by axxcident** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CTA-knapp för att börja spela](https://trello.com/c/qSG7joxs/27-cta-knapp-f%C3%B6r-att-b%C3%B6rja-spela)
