### ISSUE TITLE
Spelsida Page

### ISSUE THREAD

**Issue by saraSilvade** [axxcident/gomoku-gurus#22]

**Comment by leeparksara** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Spelsida Page](https://trello.com/c/VszCFDww/29-spelsida-page)

**Comment by saraSilvade** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Spelsida Page](https://trello.com/c/VszCFDww/29-spelsida-page)
