### ISSUE TITLE
board-component

### ISSUE THREAD

**Issue by MaximilianBakaldin** [axxcident/gomoku-gurus#8]

**Comment by axxcident** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Skapa komponent som tar fram bräda](https://trello.com/c/yqrGyFr3/17-skapa-komponent-som-tar-fram-br%C3%A4da)

**Comment by axxcident** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Skapa komponent som tar fram bräda](https://trello.com/c/yqrGyFr3/17-skapa-komponent-som-tar-fram-br%C3%A4da)
